# rxc.py: regex chopper. This strips command from transcript and puts it into a regtest.py readable script.
#
# usage: rxc.py file

import glob
import re
import i7
import sys
import os

from collections import defaultdict

ignores = []

def proc_tran(my_file, my_dir = ".", launch=False):
    if not os.path.exists(my_file) and not os.path.exists(my_file + ".txt"): sys.exit("No such file " + my_file)
    if not os.path.exists(my_file) and os.path.exists(my_file + ".txt"): my_file += ".txt"
    print("Processing", my_file)
    file_nox = re.sub("\.txt$", "", my_file, 0, re.IGNORECASE)
    cwd = os.getcwd()
    proj_name = re.sub("\.inform.*", "", cwd)
    proj_name = re.sub(".*[\\\/]", "", proj_name)
    out_file = "reg-{:s}-transcript-{:s}.txt".format(i7.revprojx(cwd), file_nox)
    fout = open(out_file, "w")
    fout.write("## {:s}.txt\n".format(file_nox))
    fout.write("##\n## generated by rxc.py\n##\n\n")
    fout.write("** game: /home/andrew/prt/debug-{:s}.ulx\n".format(proj_name))
    fout.write("** interpreter: /home/andrew/prt/glulxe -q\n\n* the-transcript")
    with open(my_file) as file:
        for (line_count, line) in enumerate(file, 1):
            if line.startswith(">"):
                for i in ignores:
                    if re.search("^> *" + i, line):
                        print("Ignoring line", line_count, line.strip())
                        continue
                if is_comment(line): continue
                if re.search("^> *[^a-z0-9]", line):
                    print("Unusual command start in line", line_count, line.strip())
                    l2 = re.sub("^> *", "", line)
                    unu[l2] += 1
                fout.write(line + "\n")
    fout.close()
    if len(unu.keys()) > 0:
        print("Unusual starts:", ', '.join(["{:s}: {:d}".format(x, unu[x]) for x in sorted(unu.keys())]))
    else:
        print("No unusual starts.")
    print(out_file, "created")
    if launch: os.system(out_file)

def is_comment(x):
    if re.search("> *[;\*]", x): return True
    return False

unu = defaultdict(int)

if len(sys.argv) == 1: sys.exit("You need to specify a file name.")
count = 1

q = []

this_dir = ""

while count < len(sys.argv):
    arg = sys.argv[1]
    if "*" in sys.argv[1]:
        q = glob.glob(sys.argv[1])
        for q1 in q:
            proc_tran(q1)
    elif arg == 'u':
        this_dir = ".."
    elif '/' in arg or "\\" in arg:
        this_dir = arg
    elif arg.startswith('i='):
        ignores = arg[2:].split(",")
    else:
        if len(q): sys.exit("Can only define one file at a time, or a glob.")
        q = [ sys.argv[1] ]
    count += 1

laun = len(q) == 1

if len(q) == 0: sys.exit("No file(s) specified.")

for qf in q: proc_tran(qf, this_dir, laun)
